### ISSUE TITLE
Unable to send SMS: unable to login: 401 Unauthorized

### ISSUE THREAD

**Issue by kepon85** [cyosp/bouyguestelecom-sms#2]
Bonjour,

Depuis quelques l'authentification ne passe plus chez moi. Est-ce que je suis seul ? Sur le formulaire Bouyges ils y ont ajouté un champ "Nom" je me dis que c'est peut être ça (car mon mot de passe est ok...)

`Unable to send SMS: unable to login: 401 Unauthorized`

David

**Comment by cyosp** [comment]
Bonjour David,

Pour m'assurer du bon fonctionnement de `bouyguestelecom-sms` je m'envoie automatiquement et quotidiennement un SMS.
A l'heure actuelle, tout est OK.

Par contre il y a 3 mois j'ai eu un soucis similaire au votre.
J'ai vérifié que la fonctionnalité d'envoi de SMS était toujours disponible.
Pour cela je me suis connecté sur l'interface de Bouygues.
C'est à ce moment qu'il m'a fallu valider la nouvelle procédure de sécurité mise en place.
Ensuite `bouyguestelecom-sms` était de nouveau opérationnel.

Pouvez-vous faire de même et me dire si cela a permis de résoudre votre soucis ?
**\/!\\** Ne pas oublier de mettre à jour le mot de passe lors de l'appel à `bouyguestelecom-sms` si vous changez le mot de passe via l'interface de Bouygues **\/!\\**.

Cordialement,
CYOSP

**Comment by kepon85** [comment]
> J'ai vérifié que la fonctionnalité d'envoi de SMS était toujours disponible.

C'est le cas et elle fonctionne en ligne : https://dl.zici.fr/1607068518-45/2020-11-19_08-52.png

> C'est à ce moment qu'il m'a fallu valider la nouvelle procédure de sécurité mise en place.

J'ai rien eu de ça...  :-/

> Pouvez-vous faire de même et me dire si cela a permis de résoudre votre soucis ?

Non du coup...

> /!\ Ne pas oublier de mettre à jour le mot de passe lors de l'appel à bouyguestelecom-sms si vous changez le mot de passe via l'interface de Bouygues /!\.

Je n'ai pas changé mon mot de passe depuis longggtemps (jamais) donc pas de problème de ce côté là je pense.

Si vous avez d'autres pistes je suis preneur,
David

**Comment by cyosp** [comment]
Bonsoir David,

Je reproduis le comportement que vous avez à partir du moment où le couple identifiant/mot de passe n'est pas correct.

Peut-être pourriez vous essayer de changer votre mot de passe via le site de Bouygues ?
Puis tester de nouveau `bouyguestelecom-sms` avec le nouveau mot de passe.

Cordialement,
CYOSP

**Comment by kepon85** [comment]
> Peut-être pourriez vous essayer de changer votre mot de passe via le site de Bouygues ?

C'est fait, mon nouveau mot de passe me permet bien de me connecter à mon compte bouygues, testé sur un autre ordi...

> Puis tester de nouveau bouyguestelecom-sms avec le nouveau mot de passe.

Même erreur 401...

> C'est à ce moment qu'il m'a fallu valider la nouvelle procédure de sécurité mise en place.

Vous vous en rappelez plus en détails ? Peut être que c'est une piste de sécu a activer ou non dans leur portail web...

**Comment by cyosp** [comment]
J'avais suivi les détails de la procédure de sécurité sans avoir besoin de configurer autre chose.

Sur quel OS exécutez-vous `bouyguestelecom-sms` ?
A-t-il été mis à jour récemment ?
Peut-être que votre mot de passe contient un où plusieurs caractères UTF-8 encodés de manière incorrecte lors du passage à `bouyguestelecom-sms`.

**Comment by kepon85** [comment]
> Sur quel OS exécutez-vous bouyguestelecom-sms ?

Debian 10

 > A-t-il été mis à jour récemment ?

Pas entre le moment ou ça fonctionnait et le moment ou ça ne fonctionnait plus...  (de mémoire) Je viens de faire un upgrade système, nouvelle tentative, même résultat...

> Peut-être que votre mot de passe contient un où plusieurs caractères UTF-8 encodés de manière incorrecte lors du passage à bouyguestelecom-sms.

Alphanumérique seulement, aucun accent, j'ai juste un "!" mais je n'en avais pas dans le précédent et j'avais le même problème..

Est-ce qu'il y a un mode débug ? (pas trouvé dans le --help) 

Comment je pourrais tester l'authentification "brute" ? Sinon par l'interface web ? Ton programme est un robot qui reprend cookies et autres du formulaire "web" ? De mon côté sur mon formulaire j'ai le champ "Nom" qui est apparût... Pas toi ? : https://dl.retzo.net/1613823873-54/2020-11-22_13-24.png je me dis que c'est peut être ça le problème...

**Comment by cyosp** [comment]
En effet je n'ai pas ce nouveau champ : ![auth](https://user-images.githubusercontent.com/12957474/99915830-51c74680-2d06-11eb-8612-95774c967b0c.png)
J'ai essayé en navigation privée mais ce nouveau champ n'apparait pas non plus.

Il est tout à fait possible que Bouygues soit en phase de déploiement canari de cette nouvelle fonctionnalité de sécurité.
Dans ce cas je vais être confronté au même problème que vous dans un futur proche.

Malheureusement sans pouvoir reproduire le soucis d'authentification, je ne peux pas le corriger.

Dès que je ne reçois plus mon SMS quotidien, je regarde de quoi il retourne pour faire évoluer `bouyguestelecom-sms`

**Comment by kepon85** [comment]
ça marche !
Si vous avez besoin de testeur ;-)

David

**Comment by cyosp** [comment]
Pour suivi, ce matin j'ai bien bien reçu mon SMS quotidien

**Comment by kepon85** [comment]
Hum j'ai une piste... 

Vous êtes sur une box internet Bouyges (ou dérivé) ? 

Car quand je me connecte en 3G en partage de connexion avec mon téléphone, donc que je sort avec une IP bouyges là il ne me demande pas de formulaire de "nom".... Du coup il s'agit peut être d'un mécanisme de sécurité "hors réseau bouyges"

Dans l'attente,
David

**Comment by cyosp** [comment]
Bonjour David,

Dans l'hypothèse d'un déploiement canari j'avais fait le test en me connectant directement avec mon téléphone et j'obtenais le même résultat qu'avec ma connexion Internet qui n'est pas assurée par une box Bouygues ou dérivée.

Votre test semble bien montrer qu'il y a un lien avec l'adresse IP et je ne pense plus à un déploiement canari.
Même si je ne comprends pas la raison pour laquelle Bouygues pourrait faire une telle vérification, peut-être est-ce lié au type d'IP ?
Est-ce que vous savez si votre box Internet sort avec une IPv4 ou un IPv6 ? Pour ma part c'est une IPv6.
Vous pouvez consulter par exemple ce site https://whatismyipaddress.com/fr/mon-ip depuis chez vous pour déterminer l'adresse IP de votre box sur Internet.

Bonne journée,
CYOSP

**Comment by kepon85** [comment]
Je confirme que depuis mon téléphone ou depuis ma connexion internet j'ai dans les 2 cas seulement une IPv4....  :-/

**Comment by cyosp** [comment]
Que l'adresse IP vue sur Internet de votre box soit encore en IPv4 ne m'étonne pas.
Par contre, pour la connexion au réseau de données (4G par exemple) de votre téléphone, je suis septique.

Pourriez-vous effectuer une nouvelle vérification en ce qui concerne votre téléphone ?
Au besoin : https://community.fs.com/fr/blog/ipv4-vs-ipv6-whats-the-difference.html

Quoiqu'il arrive le soucis que vous avez concerne votre box Internet.
Pourriez-vous regarder s'il est possible de la configurer en IPv6 vis à vis d'Internet le temps d'un test ?

**Comment by kepon85** [comment]
Je suis admin système donc l'IPv6 je vois de quoi ça parle ;-)

Et non je n'ai pas d'IPv6 sur ma box : https://dl.zici.fr/1624033992-14/Screenshot_2020-12-20_Testez_votre_IPv6_.png (OVH)

Chez bouyges avec mon partage de connexion mobile non plus : https://dl.zici.fr/1624033992-14/Screenshot_2020-12-20_Testez_votre_IPv6_bouyges_.png

Par contre j'ai un serveur qui a aussi une IPv6, et même en passant par lui (proxy socks) le résultat est le même sur l'interface bouyges : https://dl.zici.fr/1624033992-14/2020-12-20_17-32.png (demande du Nom)

Test fait avec https://test-ipv6.com/

Du coup ça ne semble pas être une bonne piste. 

Je peux fournir un accès distant SSH pour faire du proxy si vous voulez tester depuis une autre connexion...  (en privé par contre les accès > http://david.mercereau.info/contact/ )

David

**Comment by cyosp** [comment]
Ok, on range la piste de l'IPv6 :-D

Je vais regarder de mon côté si je peux accéder à l'espace client avec une autre IP que celle de ma box Internet ou celle de mon téléphone pour voir si je reproduis l'apparition de ce nouveau champ

**Comment by cyosp** [comment]
Bonjour David,

Tout d'abord je vous souhaite une bonne et heureuse année 2021 !
Pour bien commencer l'année j'ai pu adresser votre problématique.
Une nouvelle version sera disponible d'ici demain soir au plus tard.

Bonne journée,
CYOSP

**Comment by kepon85** [comment]
Belle année !
Super nouvelle. Je vois qu'il y a eu des updates. Dites moi quand vous voulez que je tests / que c'est ok pour vous...
Belle

**Comment by cyosp** [comment]
Si vous compilez vous-même le projet depuis la branche `master` l'évolution est disponible
De mon côté je suis en train de mettre en place le pipeline Github pour la génération des packages Debian

**Comment by kepon85** [comment]
ça fonctionne !!!

```
2021/01/10 22:46:31 Checking SMS left...
2021/01/10 22:46:31 SMS left before sending: 5
2021/01/10 22:46:31 Composing message to 0********
2021/01/10 22:46:31 Message composed
2021/01/10 22:46:31 Confirming message...
2021/01/10 22:46:32 Message confirmed. SMS left after sending: 4
SMS sent successfully at 2021-01-10T22:46:32+01:00. SMS left: 4.
```

Merci c'est top !

**Comment by cyosp** [comment]
Parfait :+1: :slightly_smiling_face:
